### ISSUE TITLE
Add __version__ | pep 396

### ISSUE THREAD

**Issue by DenisSalem** [roniemartinez/latex2mathml#397]
Hello :)

It would be nice to add __version__ to init.py so it would be possible to test or display from python script the version of the package.

https://peps.python.org/pep-0396/

Thank you for the good work :)

**Comment by roniemartinez** [comment]
Thanks for the suggestion.

Currently, we are pulling the version from `pyproject.toml` because this is easier to bump with `poetry version [major|minor|patch]`.

I am against hard-coding it in the source but it is possible to set the variable similar to what is implemented in https://github.com/roniemartinez/latex2mathml/blob/241a4fadf9a82c3512752fe2f3bbee648c6b956b/latex2mathml/converter.py#L567

This scenario is similar to distutils2 in the above PEP: https://peps.python.org/pep-0396/#distutils2

@DenisSalem Do you want to write the code for this?

**Comment by DenisSalem** [comment]
Well, as long as I can do something like

```
from latex2mathml import version
```

and / or

```
from latex2mathml import __version__
```

I guess I'm fine with this implementation :)

Thank you for the quick reply !

**Comment by DenisSalem** [comment]
Just made a pull request :)
